version: '3.8'

services:
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    restart: unless-stopped
    ports:
      - "11011:11011"
    volumes:
      - /home/bence/torrent/data/cleanuparr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC