services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Budapest
      - PUID=1000
      - PGID=1000
      - nodeName=GPU_Node
      - serverIP=192.168.1.85
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - transcodegpuWorkers=1
      - transcodecpuWorkers=0
      - healthcheckgpuWorkers=0
      - healthcheckcpuWorkers=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /home/bence/tdarr/configs:/app/configs
      - /home/bence/tdarr/logs:/app/logs
      - /mnt/media:/media 
      - /home/bence/tdarr/temp:/temp 
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu] # Nvidia GPU-hoz