services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Budapest
      - PUID=1000
      - PGID=1000
      - nodeName=CPU_Node
      - serverIP=192.168.1.85
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - transcodegpuWorkers=0 # GPU kikapcsolva
      - transcodecpuWorkers=4 # CPU bekapcsolva (Ezt a számot nyugodtan átírhatod, attól függően, hány magos a processzorod!)
      - healthcheckgpuWorkers=0
      - healthcheckcpuWorkers=0
    volumes:
      - /home/bence/tdarr/configs:/app/configs
      - /home/bence/tdarr/logs:/app/logs
      - /mnt/media:/media 
      - /home/bence/tdarr/temp:/temp