services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-latest}
    container_name: open-webui
    environment:
      - "OPENAI_API_BASE_URL=http://litellm:4000"
      - "OPENAI_API_KEY=any-random-string"
    volumes:
      - /mnt/hdd/openwebui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3003}:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped