version: '3.8'

services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    init: true
    restart: unless-stopped
    user: "1006:1005"
    ports:
      - "5055:5055"
    environment:
      - LOG_LEVEL=debug
      - TZ=Eurpoe/Budapest
      - PORT=5055
    volumes:
      - /home/bence/torrent/data/jellyseerr/config:/app/config
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 20s