log:
  level: info

runner:
  file: .runner
  capacity: 2         # Egyszerre hány pipeline futhat párhuzamosan
  timeout: 3h
  shutdown_timeout: 5s
  insecure: true

container:
  network: ""         # DinD esetén hagyd üresen, mert a DinD saját belső hálózatot használ
  privileged: true   # A futó jobok konténerei ne legyenek privileged módban
  valid_volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  options: "-v /var/run/docker.sock:/var/run/docker.sock"
  workdir: /workspace
