---
- name: update
  hosts: torrent, docker, docker2, proxmox
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400 #One day
        autoclean: true
        autoremove: true