version: "3.8"
name: docs

services:
  docs-server:
    image: ghcr.io/bencegyurus/gyurus-docs:sha-c18695b
    networks:
      - internal
      - proxy
    port:
      - "81:80"
    restart: always
networks:
  internal:
    driver: bridge
  proxy:
    external: true
