version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9444:9443"
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/hdd/portainer:/data
volumes:
  portainer_data:
