version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    networks:
      - "proxy"
      - "internal"
    ports:
      - "8000:8000"
      - "9444:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/hdd/portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.gyurus.hu`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
volumes:
  portainer_data:


networks:
  internal:
    driver: bridge
  proxy:
    external: true
