version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9444:9443"
      - "9001:9000"
    volumes:
      - /mnt/hdd/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /mnt/hdd/prometheus:/prometheus
volumes:
  portainer_data:
