services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MAX_PLAYERS: 10
      ONLINE_MODE: "FALSE"
      SPAWN_PROTECTION: "TRUE"
      PLAYER_IDLE_TIMEOUT: 5
      WHITELIST: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /mnt/hdd/mc:/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2g