version: "3.8"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8082:8080"
    command:
      - --housekeeping_interval=30s
      - --max_housekeeping_interval=60s
      - --allow_dynamic_housekeeping=true
      - --global_housekeeping_interval=1m
      - --docker_only=true
      - --disable_root_cgroup_stats=true
      - --disable_metrics=accelerator,cpu_topology,memory_numa,tcp,udp,advtcp,process,sched,hugetlb,referenced_memory,resctrl,percpu
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9101:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
