services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/tramission:/config
      - ./data:/data
      - ./data/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: 10.5.0.5
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/sonarr:/config
      - ./data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: 10.5.0.6
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/radarr:/config
      - ./data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: 10.5.0.7
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/powlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: 10.5.0.9
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
      - type: bind
        source: ./data/media
        target: /media
        read_only: true
      - type: bind
        source: ./data/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: "unless-stopped"
    environment:
      - JELLYFIN_PublishedServerUrl=http://tv.gyurus.hu
    extra_hosts:
      - "host.docker.internal:host-gateway"
  plex:
    image: plexinc/pms-docker:latest
    privileged: true
    container_name: plex
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - ADVERTISE_IP=https://stream.gyurus.hu
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/plexmediaserver:/config
      - ./data/media:/mnt/tv
      - ./data/media:/mnt/movies
    restart: unless-stopped
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /home/bence/torrent/data/komga
        target: /config
      - type: bind
        source: /home/bence/torrent/data/downloads/complete/books
        target: /data
    ports:
      - 25600:25600
    user: "1000:1000"
    restart: unless-stopped
  navidrome:
    image: deluan/navidrome:latest
    user: 1001:1001 # should be owner of volumes
    env_file:
      - .env
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "/home/bence/torrent/data/navidome:/data"
      - "/home/bence/torrent/data/media/music:/music:ro"
  spooty:
    image: raiper34/spooty:latest
    container_name: spooty
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /home/bence/torrent/data/music:/spooty/backend/downloads
    env_file:
      - .env

  
  feishin:
    image: ghcr.io/jeffvli/feishin:latest
    container_name: feishin
    ports:
      - "9180:9180"
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    container_name: spotiarr-redis
    restart: unless-stopped
    volumes:
      - ./redis:/data
  
  spotiarr:
    image: mralexandersaavedra/spotiarr:latest
    container_name: spotiarr
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - /home/bence/torrent/data/spotiarr:/spotiarr/config
      - /home/bence/torrent/data/media/music:/downloads
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=https://spot.gyurus.hu/api/auth/spotify/callback
      # Public IP or Domain where SpotiArr will be accessed.
      # Required for Spotify Auth Redirect.
      - PUBLIC_HOST=192.168.1.85
    depends_on:
      - redis
  

  aonsoku:
    container_name: aonsoku
    image: ghcr.io/victoralvesf/aonsoku:latest
    restart: unless-stopped
    ports:
      - 8080:8080

  maintainerr:
        image: ghcr.io/maintainerr/maintainerr:latest # or maintainerr/maintainerr:latest
        container_name: maintainerr
        user: 1000:1000
        volumes:
          - type: bind
            source: ./data/media
            target: /opt/data
        environment:
          - TZ=Europe/Budapest
        ports:
          - 6246:6246
        restart: unless-stopped

networks:
  media-server:
    name: media-server
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
