apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bencegyurus/statistics-backend:latest
          imagePullPolicy: Never
          env:
            - name: GIN_MODE
              value: "release"
            - name: BACKEND
              value: "backend"
            - name: BACKEND_PORT
              value: "3001"
            - name: DB_NAME
              value: "timescaledb"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_HOST
              value: "timescaledb"
            - name: PREFIX
              value: "/api/v1"
          ports:
          - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bencegyurus/statistics-frontend:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: docker.io/timescale/timescaledb:latest-pg12
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: "timescaledb"
          ports:
            - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: timescaledb
spec:
  type: ClusterIP
  selector:
    app: timescaledb
  ports:
    - port: 5432
      targetPort: 5432